name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - v4

# env:
#   THEME_NAME: tokyo-night

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
        #   submodules: recursive
        #   token: ${{ secrets.GH_PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup @antfu/ni #slidev
        run: npm i -g @antfu/ni

      - name: Install Dependencies
        run:  |
          npm ci
          npm install -D slidev/cli

    #   - name: Fetch Quartz Theme
    #     run: curl -s -S https://raw.githubusercontent.com/saberzero1/quartz-themes/master/action.sh | bash -s -- $THEME_NAME

    #   - name: Copy content from submodule
    #     run: |
    #       mkdir -p ./content
    #       cp -r ./submodules/content-repo/content/* ./content/

      - name: Build Quartz
        run: npx quartz build

      - name: Build all Slidev .md files
        run: |
         mkdir -p public/slidev
          find slides -type f -name "*.md" | while read file; do
            relpath="${file#slides/}"                       # e.g. topic1/sub/slide.md
            name="${relpath%.md}"                           # e.g. topic1/sub/slide
            outdir="dist/$name"                             # e.g. dist/topic1/sub/slide
            targetdir="public/slidev/$name"                 # e.g. public/slidev/topic1/sub/slide

            echo "📦 Building $file → $targetdir"

            npx slidev build "$file" --out "$outdir"

            mkdir -p "$targetdir"
            cp -r "$outdir/"* "$targetdir/"
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
